#version: '3.8'

# https://hub.docker.com/r/zepai/graphiti
# http://localhost:8000
# http://localhost:8000/docs
services:
  graphiti:
    image: my/graphiti:0.10.5
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - MODEL_NAME=${MODEL_NAME}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - neo4j-graphiti
  # http://localhost:17474/browser/
  neo4j-graphiti:
    image: neo4j:5.25-community
    ports:
      - "17474:7474"  # HTTP
      - "17687:7687"  # Bolt
    volumes:
      - ./neo4j-data:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
