
server:
  port: 8201

spring:
  application:
    name: models-openai
  ai:
    openai:
      base-url: http://localhost:1234
      api-key: test
      chat:
        options:
          model: deepseek-r1-distill-qwen-7b
          temperature: 0.7
