debug: true

spring:
  application:
    name: demo-springai-app
  ai:
    dashscope:
#      agent:
#        app-id: put-your-app-id-here
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        enabled: true
        options:
          model: deepseek-r1
