debug: true

logging:
  level:
    io.modelcontextprotocol: debug
    org.springframework.ai: debug
    org.springframework.web.reactive.function.client: debug
    com.demo.ai.spring.app: debug

server:
  port: 8181
  servlet:
    encoding:
      charset: UTF-8
      force-response: true  # 解决响应Flux<T> "text/event-stream" 没有添加"charset=UTF-8"的问题

spring:
  main:
    web-application-type: servlet
  application:
    name: demo-springai-app
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        enabled: true
        options:
          model: deepseek-v3
    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: true
        stdio: #本地MCP服务配置
          servers-configuration: classpath:/mcp-servers-config.json  # 推荐使用
          connections:
            amap-maps-mcp-server:
              command: npx
              args:
                - "-y"
                - "@amap/amap-maps-mcp-server"
              env:
                AMAP_MAPS_API_KEY: ${AMAP_MAPS_API_KEY}
