
server:
  port: 8102

spring:
  application:
    name: mcp-client-starter-webflux
  ai:
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        sse:
          connections:
            weather-server:
              url: http://localhost:8001
#    openai:
#      base-url: http://localhost:1234
#      api-key: test
#      chat:
#        options:
#          model: deepseek-r1-distill-qwen-7b
#          temperature: 0.7
